// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Toaster } from "react-hot-toast";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         suppressHydrationWarning
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         data-lk-theme="default"
//       >
//         <Toaster />
//         {children}
//       </body>
//     </html>
//   );
// }

import "../styles/globals.css";
import "@livekit/components-styles";
import "@livekit/components-styles/prefabs";
import type { Metadata, Viewport } from "next";
import { Toaster } from "react-hot-toast";
import CallUIOverlay from "./components/CallUIOverlay";

export const metadata: Metadata = {
  title: {
    default: "LiveKit Meet | Conference app build with LiveKit open source",
    template: "%s",
  },
  description:
    "LiveKit is an open source WebRTC project that gives you everything needed to build scalable and real-time audio and/or video experiences in your applications.",
  twitter: {
    creator: "@livekitted",
    site: "@livekitted",
    card: "summary_large_image",
  },
  openGraph: {
    url: "https://meet.livekit.io",
    images: [
      {
        url: "https://meet.livekit.io/images/livekit-meet-open-graph.png",
        width: 2000,
        height: 1000,
        type: "image/png",
      },
    ],
    siteName: "LiveKit Meet",
  },
  icons: {
    icon: {
      rel: "icon",
      url: "/favicon.ico",
    },
    apple: [
      {
        rel: "apple-touch-icon",
        url: "/images/livekit-apple-touch.png",
        sizes: "180x180",
      },
      {
        rel: "mask-icon",
        url: "/images/livekit-safari-pinned-tab.svg",
        color: "#070707",
      },
    ],
  },
};

export const viewport: Viewport = {
  themeColor: "#070707",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body data-lk-theme="default"> */}
      <body data-lk-theme="default">
        {/* <Toaster /> */}
        <Toaster position="top-center" toastOptions={{ duration: 4000 }} />
        <CallUIOverlay />
        {children}
      </body>
    </html>
  );
}
